### ISSUE TITLE
Now uncompatible with 1.5.2

### ISSUE THREAD

**Issue by Hiztaar** [sweatty1/BannerlordMinorClanTroopRecruitment#5]
The current build does not work on 1.5.2+ anymore.

**Comment by sweatty1** [comment]
This should be fixed with #6 and release 1.1.2 Removed the additional submodule check for Mod Configuration Menu 3.1.9 Which was causing the crash because most users had moved on to the 4+ beta/release of the Mod Configuration Menu. #

**Comment by Hiztaar** [comment]
Actually it's still crashing for me on the latest version...

**Comment by Hiztaar** [comment]
[rgl_log_21776.txt](https://github.com/sweatty1/BannerlordMinorClanTroopRecruitment/files/5404376/rgl_log_21776.txt)

**Comment by sweatty1** [comment]
From looking at your log it seems you are missing the MCMv4 MCMv3 Integration mod of Mod Configuration Menu. Below are the mod/mod order I use to test the game in both 1.5.2 and 1.5.3.  Your provided log also lists that MCMv4 ModLib v1/v13 Integration is also missing and while that isn't required for my specific mod other mods may act up.

Harmony
Butterlib
UIExtenderEx
Mod Configuration Menu V4
MCMv4 MCMv3 Integration
MCMv4 ModLib v1/v13 Integration
...
Base Game Modules
...
This mod

**Comment by Hiztaar** [comment]
It works that way. Thanks!
